# Generated by Django 5.1 on 2024-10-08 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_rename_finalizada_tarefa_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pessoa_notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notificacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
