# Generated by Django 5.1 on 2024-10-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_anexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tasks',
            new_name='fk_task',
        ),
    ]
